[2025-02-23T18:18:46.284+0530] {processor.py:157} INFO - Started process (PID=6392) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:18:46.284+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:18:46.285+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:18:46.285+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:18:46.305+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:18:46.303+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:18:46.305+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:18:46.305+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:18:46.305+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:18:46.351+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-23T18:25:19.126+0530] {processor.py:157} INFO - Started process (PID=7377) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:25:19.127+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:25:19.127+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:25:19.127+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:25:19.148+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:25:19.146+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:25:19.148+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:25:19.148+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:25:19.148+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:25:19.194+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T18:26:52.277+0530] {processor.py:157} INFO - Started process (PID=7603) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:26:52.278+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:26:52.278+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:26:52.278+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:26:52.299+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:26:52.297+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:26:52.299+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:26:52.299+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:26:52.299+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:26:52.346+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T18:28:29.671+0530] {processor.py:157} INFO - Started process (PID=7823) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:28:29.673+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:28:29.673+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:28:29.673+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:28:29.695+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:28:29.693+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:28:29.695+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:28:29.695+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:28:29.695+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:28:29.745+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-23T18:29:54.720+0530] {processor.py:157} INFO - Started process (PID=8004) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:29:54.722+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:29:54.722+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:29:54.722+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:29:54.746+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:29:54.744+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:29:54.746+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:29:54.746+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:29:54.746+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:29:54.795+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2025-02-23T18:31:35.659+0530] {processor.py:157} INFO - Started process (PID=8183) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:31:35.660+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:31:35.661+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:31:35.661+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:31:35.683+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:31:35.682+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:31:35.683+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:31:35.683+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:31:35.684+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:31:35.733+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-23T18:33:15.381+0530] {processor.py:157} INFO - Started process (PID=8365) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:33:15.382+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:33:15.382+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:33:15.382+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:33:15.404+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:33:15.402+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:33:15.404+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:33:15.404+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:33:15.404+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:33:15.452+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-23T18:35:41.905+0530] {processor.py:157} INFO - Started process (PID=8783) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:35:41.906+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:35:41.906+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:35:41.906+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:35:41.931+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:35:41.929+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:35:41.931+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:35:41.931+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:35:41.931+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:35:41.978+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-23T18:37:14.335+0530] {processor.py:157} INFO - Started process (PID=8966) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:37:14.336+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:37:14.337+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:37:14.337+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:37:14.360+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:37:14.358+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:37:14.360+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:37:14.360+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:37:14.360+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:37:14.410+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2025-02-23T18:38:42.020+0530] {processor.py:157} INFO - Started process (PID=9168) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:38:42.022+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:38:42.022+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:38:42.022+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:38:42.043+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:38:42.041+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:38:42.043+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:38:42.043+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:38:42.044+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:38:42.091+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T18:40:18.148+0530] {processor.py:157} INFO - Started process (PID=9342) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:40:18.150+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:40:18.150+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:40:18.150+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:40:18.171+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:40:18.169+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:40:18.171+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:40:18.171+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:40:18.171+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:40:18.218+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-23T18:41:31.034+0530] {processor.py:157} INFO - Started process (PID=9512) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:41:31.035+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:41:31.035+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:41:31.035+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:41:31.056+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:41:31.054+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:41:31.056+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:41:31.056+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:41:31.056+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:41:31.103+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T18:43:02.714+0530] {processor.py:157} INFO - Started process (PID=9670) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:43:02.715+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:43:02.715+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:43:02.715+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:43:02.735+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:43:02.733+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:43:02.735+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:43:02.735+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:43:02.735+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:43:02.782+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T18:44:44.959+0530] {processor.py:157} INFO - Started process (PID=9880) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:44:44.960+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:44:44.960+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:44:44.960+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:44:44.981+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:44:44.979+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:44:44.981+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:44:44.981+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:44:44.981+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:44:45.027+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T18:46:25.683+0530] {processor.py:157} INFO - Started process (PID=10059) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:46:25.685+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:46:25.685+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:46:25.685+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:46:25.715+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:46:25.712+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:46:25.715+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:46:25.715+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:46:25.715+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:46:25.776+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2025-02-23T18:47:59.969+0530] {processor.py:157} INFO - Started process (PID=10218) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:47:59.970+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:47:59.970+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:47:59.970+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:47:59.993+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:47:59.991+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:47:59.993+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:47:59.993+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:47:59.994+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:48:00.043+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2025-02-23T18:49:35.400+0530] {processor.py:157} INFO - Started process (PID=10389) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:49:35.401+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:49:35.401+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:49:35.401+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:49:35.424+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:49:35.422+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:49:35.424+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:49:35.424+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:49:35.424+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:49:35.472+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-23T18:51:03.857+0530] {processor.py:157} INFO - Started process (PID=10581) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:51:03.858+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:51:03.858+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:51:03.858+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:51:03.879+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:51:03.877+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:51:03.879+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:51:03.879+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:51:03.879+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:51:03.925+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T18:52:44.554+0530] {processor.py:157} INFO - Started process (PID=10750) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:52:44.554+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:52:44.554+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:52:44.554+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:52:44.576+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:52:44.574+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:52:44.576+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:52:44.576+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:52:44.576+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:52:44.625+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-23T18:54:11.252+0530] {processor.py:157} INFO - Started process (PID=10931) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:54:11.253+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:54:11.253+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:54:11.253+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:54:11.275+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:54:11.273+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:54:11.275+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:54:11.275+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:54:11.275+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:54:11.323+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T18:55:50.149+0530] {processor.py:157} INFO - Started process (PID=11118) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:55:50.149+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:55:50.150+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:55:50.149+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:55:50.170+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:55:50.169+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:55:50.170+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:55:50.170+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:55:50.171+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:55:50.217+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T18:57:27.432+0530] {processor.py:157} INFO - Started process (PID=11287) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:57:27.433+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T18:57:27.434+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:57:27.433+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:57:27.455+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:57:27.453+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T18:57:27.455+0530] {logging_mixin.py:154} INFO - [2025-02-23T18:57:27.455+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T18:57:27.455+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T18:57:27.502+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-23T19:14:32.024+0530] {processor.py:157} INFO - Started process (PID=11574) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:14:32.024+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T19:14:32.025+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:14:32.025+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:14:32.045+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:14:32.043+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T19:14:32.045+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:14:32.045+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T19:14:32.045+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:14:32.090+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-23T19:16:12.245+0530] {processor.py:157} INFO - Started process (PID=11757) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:16:12.246+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T19:16:12.246+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:16:12.246+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:16:12.267+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:16:12.265+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T19:16:12.267+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:16:12.267+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T19:16:12.267+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:16:12.313+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T19:32:54.363+0530] {processor.py:157} INFO - Started process (PID=11967) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:32:54.364+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T19:32:54.364+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:32:54.364+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:32:54.386+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:32:54.384+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T19:32:54.386+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:32:54.386+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T19:32:54.386+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:32:54.432+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T19:34:37.846+0530] {processor.py:157} INFO - Started process (PID=12172) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:34:37.846+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T19:34:37.846+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:34:37.846+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:34:37.866+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:34:37.865+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T19:34:37.867+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:34:37.867+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T19:34:37.867+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:34:37.913+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T19:36:21.187+0530] {processor.py:157} INFO - Started process (PID=12360) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:36:21.188+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T19:36:21.188+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:36:21.188+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:36:21.208+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:36:21.207+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T19:36:21.209+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:36:21.208+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T19:36:21.209+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:36:21.254+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-23T19:53:13.957+0530] {processor.py:157} INFO - Started process (PID=12600) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:53:13.958+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T19:53:13.958+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:53:13.958+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:53:13.980+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:53:13.978+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T19:53:13.980+0530] {logging_mixin.py:154} INFO - [2025-02-23T19:53:13.980+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T19:53:13.980+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T19:53:14.025+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T20:07:37.224+0530] {processor.py:157} INFO - Started process (PID=12761) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:07:37.225+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:07:37.225+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:07:37.225+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:07:37.246+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:07:37.244+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:07:37.246+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:07:37.246+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:07:37.246+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:07:37.292+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T20:09:12.889+0530] {processor.py:157} INFO - Started process (PID=12959) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:09:12.890+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:09:12.891+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:09:12.891+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:09:12.910+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:09:12.909+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:09:12.911+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:09:12.911+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:09:12.911+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:09:12.956+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-23T20:10:50.177+0530] {processor.py:157} INFO - Started process (PID=13148) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:10:50.178+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:10:50.178+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:10:50.178+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:10:50.199+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:10:50.197+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:10:50.199+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:10:50.199+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:10:50.199+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:10:50.246+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T20:12:20.122+0530] {processor.py:157} INFO - Started process (PID=13314) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:12:20.123+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:12:20.123+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:12:20.123+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:12:20.145+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:12:20.143+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:12:20.145+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:12:20.145+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:12:20.145+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:12:20.194+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-23T20:13:51.913+0530] {processor.py:157} INFO - Started process (PID=13476) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:13:51.914+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:13:51.915+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:13:51.915+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:13:51.935+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:13:51.934+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:13:51.935+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:13:51.935+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:13:51.936+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:13:51.981+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T20:15:29.837+0530] {processor.py:157} INFO - Started process (PID=13664) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:15:29.838+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:15:29.839+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:15:29.839+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:15:29.859+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:15:29.857+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:15:29.859+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:15:29.859+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:15:29.859+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:15:29.905+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T20:16:59.459+0530] {processor.py:157} INFO - Started process (PID=13833) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:16:59.460+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:16:59.461+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:16:59.461+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:16:59.481+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:16:59.480+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:16:59.481+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:16:59.481+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:16:59.481+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:16:59.527+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T20:18:26.970+0530] {processor.py:157} INFO - Started process (PID=13989) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:18:26.971+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:18:26.971+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:18:26.971+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:18:26.992+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:18:26.990+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:18:26.992+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:18:26.992+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:18:26.992+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:18:27.039+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T20:20:01.301+0530] {processor.py:157} INFO - Started process (PID=14157) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:20:01.302+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:20:01.302+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:20:01.302+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:20:01.323+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:20:01.321+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:20:01.323+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:20:01.323+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:20:01.323+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:20:01.370+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-23T20:21:36.852+0530] {processor.py:157} INFO - Started process (PID=14322) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:21:36.853+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:21:36.854+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:21:36.854+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:21:36.875+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:21:36.873+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:21:36.875+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:21:36.875+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:21:36.875+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:21:36.921+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T20:23:11.906+0530] {processor.py:157} INFO - Started process (PID=14487) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:23:11.907+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:23:11.907+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:23:11.907+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:23:11.928+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:23:11.926+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:23:11.928+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:23:11.928+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:23:11.928+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:23:11.975+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T20:24:48.280+0530] {processor.py:157} INFO - Started process (PID=14648) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:24:48.281+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:24:48.281+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:24:48.281+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:24:48.302+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:24:48.300+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:24:48.302+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:24:48.302+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:24:48.302+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:24:48.349+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T20:26:27.791+0530] {processor.py:157} INFO - Started process (PID=14821) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:26:27.792+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:26:27.792+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:26:27.792+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:26:27.813+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:26:27.812+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:26:27.814+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:26:27.814+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:26:27.814+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:26:27.861+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-23T20:27:53.722+0530] {processor.py:157} INFO - Started process (PID=14988) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:27:53.723+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:27:53.723+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:27:53.723+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:27:53.745+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:27:53.743+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:27:53.745+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:27:53.745+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:27:53.745+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:27:53.791+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T20:29:23.350+0530] {processor.py:157} INFO - Started process (PID=15152) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:29:23.351+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:29:23.351+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:29:23.351+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:29:23.373+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:29:23.371+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:29:23.373+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:29:23.373+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:29:23.373+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:29:23.420+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-23T20:31:07.414+0530] {processor.py:157} INFO - Started process (PID=15329) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:31:07.414+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:31:07.415+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:31:07.415+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:31:07.437+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:31:07.435+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:31:07.437+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:31:07.437+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:31:07.437+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:31:07.486+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-23T20:32:46.170+0530] {processor.py:157} INFO - Started process (PID=15503) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:32:46.171+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:32:46.172+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:32:46.172+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:32:46.194+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:32:46.192+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:32:46.195+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:32:46.195+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:32:46.195+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:32:46.245+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2025-02-23T20:34:17.461+0530] {processor.py:157} INFO - Started process (PID=15669) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:34:17.462+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:34:17.462+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:34:17.462+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:34:17.483+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:34:17.481+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:34:17.483+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:34:17.483+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:34:17.483+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:34:17.530+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T20:35:45.447+0530] {processor.py:157} INFO - Started process (PID=15822) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:35:45.448+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:35:45.448+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:35:45.448+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:35:45.472+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:35:45.470+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:35:45.472+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:35:45.472+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:35:45.472+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:35:45.522+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2025-02-23T20:37:25.115+0530] {processor.py:157} INFO - Started process (PID=15998) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:37:25.116+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:37:25.116+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:37:25.116+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:37:25.137+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:37:25.135+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:37:25.137+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:37:25.137+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:37:25.137+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:37:25.184+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-23T20:38:59.025+0530] {processor.py:157} INFO - Started process (PID=16165) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:38:59.026+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:38:59.026+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:38:59.026+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:38:59.047+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:38:59.046+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:38:59.048+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:38:59.048+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:38:59.048+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:38:59.095+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-23T20:40:30.257+0530] {processor.py:157} INFO - Started process (PID=16337) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:40:30.258+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:40:30.258+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:40:30.258+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:40:30.280+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:40:30.278+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:40:30.280+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:40:30.280+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:40:30.280+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:40:30.327+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T20:42:09.156+0530] {processor.py:157} INFO - Started process (PID=16528) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:42:09.157+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:42:09.157+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:42:09.157+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:42:09.179+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:42:09.177+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:42:09.179+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:42:09.179+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:42:09.179+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:42:09.228+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-23T20:43:52.475+0530] {processor.py:157} INFO - Started process (PID=16737) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:43:52.476+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:43:52.476+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:43:52.476+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:43:52.498+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:43:52.496+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:43:52.498+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:43:52.498+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:43:52.498+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:43:52.547+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-23T20:45:34.320+0530] {processor.py:157} INFO - Started process (PID=16957) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:45:34.321+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:45:34.321+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:45:34.321+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:45:34.342+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:45:34.340+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:45:34.342+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:45:34.342+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:45:34.342+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:45:34.390+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T20:47:28.443+0530] {processor.py:157} INFO - Started process (PID=17174) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:47:28.444+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T20:47:28.444+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:47:28.444+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:47:28.467+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:47:28.465+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T20:47:28.467+0530] {logging_mixin.py:154} INFO - [2025-02-23T20:47:28.467+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T20:47:28.467+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T20:47:28.516+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-23T21:06:57.642+0530] {processor.py:157} INFO - Started process (PID=17380) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:06:57.643+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T21:06:57.644+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:06:57.644+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:06:57.664+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:06:57.662+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T21:06:57.664+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:06:57.664+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T21:06:57.664+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:06:57.709+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-23T21:13:21.339+0530] {processor.py:157} INFO - Started process (PID=17587) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:13:21.340+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T21:13:21.340+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:13:21.340+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:13:21.360+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:13:21.358+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T21:13:21.360+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:13:21.360+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T21:13:21.360+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:13:21.406+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-23T21:14:58.026+0530] {processor.py:157} INFO - Started process (PID=17751) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:14:58.027+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T21:14:58.027+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:14:58.027+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:14:58.049+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:14:58.047+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T21:14:58.049+0530] {logging_mixin.py:154} INFO - [2025-02-23T21:14:58.049+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T21:14:58.049+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T21:14:58.096+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T22:53:50.591+0530] {processor.py:157} INFO - Started process (PID=22174) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:53:50.592+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T22:53:50.592+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:53:50.592+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:53:50.614+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:53:50.612+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T22:53:50.614+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:53:50.614+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T22:53:50.614+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:53:50.662+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-23T22:55:24.422+0530] {processor.py:157} INFO - Started process (PID=22344) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:55:24.423+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T22:55:24.424+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:55:24.424+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:55:24.449+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:55:24.446+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T22:55:24.449+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:55:24.449+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T22:55:24.449+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:55:24.499+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.077 seconds
[2025-02-23T22:56:58.019+0530] {processor.py:157} INFO - Started process (PID=22504) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:56:58.019+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T22:56:58.019+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:56:58.019+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:56:58.039+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:56:58.037+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T22:56:58.039+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:56:58.039+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T22:56:58.039+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:56:58.086+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T22:58:41.894+0530] {processor.py:157} INFO - Started process (PID=22696) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:58:41.895+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T22:58:41.895+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:58:41.895+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:58:41.915+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:58:41.914+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T22:58:41.916+0530] {logging_mixin.py:154} INFO - [2025-02-23T22:58:41.916+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T22:58:41.916+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T22:58:41.962+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T23:00:14.181+0530] {processor.py:157} INFO - Started process (PID=22972) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:00:14.182+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:00:14.182+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:00:14.182+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:00:14.203+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:00:14.201+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:00:14.203+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:00:14.203+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:00:14.203+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:00:14.252+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T23:05:14.526+0530] {processor.py:157} INFO - Started process (PID=23320) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:05:14.527+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:05:14.528+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:05:14.528+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:05:14.549+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:05:14.547+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:05:14.549+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:05:14.549+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:05:14.549+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:05:14.598+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-23T23:06:49.328+0530] {processor.py:157} INFO - Started process (PID=23558) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:06:49.328+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:06:49.328+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:06:49.328+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:06:49.350+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:06:49.348+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:06:49.350+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:06:49.350+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:06:49.350+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:06:49.399+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T23:08:30.216+0530] {processor.py:157} INFO - Started process (PID=23740) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:08:30.217+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:08:30.217+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:08:30.217+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:08:30.238+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:08:30.236+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:08:30.238+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:08:30.238+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:08:30.238+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:08:30.285+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T23:10:07.747+0530] {processor.py:157} INFO - Started process (PID=23950) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:10:07.748+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:10:07.748+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:10:07.748+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:10:07.771+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:10:07.769+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:10:07.771+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:10:07.771+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:10:07.771+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:10:07.818+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T23:11:39.647+0530] {processor.py:157} INFO - Started process (PID=24513) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:11:39.648+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:11:39.648+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:11:39.648+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:11:39.669+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:11:39.667+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:11:39.669+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:11:39.669+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:11:39.669+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:11:39.716+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-23T23:13:09.671+0530] {processor.py:157} INFO - Started process (PID=24698) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:13:09.672+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:13:09.673+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:13:09.673+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:13:09.697+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:13:09.694+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:13:09.697+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:13:09.697+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:13:09.697+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:13:09.754+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.083 seconds
[2025-02-23T23:14:42.768+0530] {processor.py:157} INFO - Started process (PID=24874) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:14:42.769+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:14:42.769+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:14:42.769+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:14:42.790+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:14:42.788+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:14:42.791+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:14:42.790+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:14:42.791+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:14:42.838+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T23:16:11.508+0530] {processor.py:157} INFO - Started process (PID=25060) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:16:11.508+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:16:11.508+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:16:11.508+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:16:11.531+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:16:11.529+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:16:11.531+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:16:11.531+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:16:11.531+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:16:11.581+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-23T23:17:50.298+0530] {processor.py:157} INFO - Started process (PID=25237) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:17:50.299+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T23:17:50.299+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:17:50.299+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:17:50.319+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:17:50.317+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T23:17:50.319+0530] {logging_mixin.py:154} INFO - [2025-02-23T23:17:50.319+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T23:17:50.319+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T23:17:50.365+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-24T00:25:39.346+0530] {processor.py:157} INFO - Started process (PID=25467) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-24T00:25:39.347+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-24T00:25:39.348+0530] {logging_mixin.py:154} INFO - [2025-02-24T00:25:39.347+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-24T00:25:39.369+0530] {logging_mixin.py:154} INFO - [2025-02-24T00:25:39.367+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-24T00:25:39.369+0530] {logging_mixin.py:154} INFO - [2025-02-24T00:25:39.369+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-24T00:25:39.369+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-24T00:25:39.414+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-24T00:42:18.397+0530] {processor.py:157} INFO - Started process (PID=25618) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-24T00:42:18.398+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-24T00:42:18.398+0530] {logging_mixin.py:154} INFO - [2025-02-24T00:42:18.398+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-24T00:42:18.419+0530] {logging_mixin.py:154} INFO - [2025-02-24T00:42:18.417+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-24T00:42:18.419+0530] {logging_mixin.py:154} INFO - [2025-02-24T00:42:18.419+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-24T00:42:18.419+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-24T00:42:18.464+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
