[2025-02-26T13:40:33.355+0530] {processor.py:157} INFO - Started process (PID=9991) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:40:33.356+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:40:33.356+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:40:33.356+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:40:33.377+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:40:33.375+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:40:33.377+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:40:33.377+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:40:33.377+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:40:33.424+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T13:42:06.949+0530] {processor.py:157} INFO - Started process (PID=10252) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:42:06.950+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:42:06.950+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:42:06.950+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:42:06.970+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:42:06.969+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:42:06.970+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:42:06.970+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:42:06.970+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:42:07.016+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T13:43:55.965+0530] {processor.py:157} INFO - Started process (PID=10381) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:43:55.966+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:43:55.966+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:43:55.966+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:43:55.987+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:43:55.985+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:43:55.987+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:43:55.987+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:43:55.987+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:43:56.033+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T13:47:02.379+0530] {processor.py:157} INFO - Started process (PID=10519) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:47:02.380+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:47:02.380+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:47:02.380+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:47:02.401+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:47:02.399+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:47:02.401+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:47:02.401+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:47:02.401+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:47:02.447+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T13:48:37.736+0530] {processor.py:157} INFO - Started process (PID=10644) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:48:37.736+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:48:37.737+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:48:37.737+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:48:37.756+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:48:37.754+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:48:37.756+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:48:37.756+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:48:37.756+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:48:37.801+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2025-02-26T13:50:04.339+0530] {processor.py:157} INFO - Started process (PID=10756) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:50:04.339+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:50:04.339+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:50:04.339+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:50:04.359+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:50:04.357+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:50:04.359+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:50:04.359+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:50:04.359+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:50:04.404+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2025-02-26T13:51:31.662+0530] {processor.py:157} INFO - Started process (PID=10880) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:51:31.663+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:51:31.664+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:51:31.664+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:51:31.684+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:51:31.683+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:51:31.684+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:51:31.684+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:51:31.684+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:51:31.729+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-26T13:54:03.360+0530] {processor.py:157} INFO - Started process (PID=11013) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:54:03.361+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:54:03.361+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:54:03.361+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:54:03.382+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:54:03.380+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:54:03.382+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:54:03.382+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:54:03.382+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:54:03.427+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T13:55:36.825+0530] {processor.py:157} INFO - Started process (PID=11136) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:55:36.825+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:55:36.826+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:55:36.826+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:55:36.848+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:55:36.846+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:55:36.848+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:55:36.848+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:55:36.848+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:55:36.896+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-26T13:57:12.491+0530] {processor.py:157} INFO - Started process (PID=11261) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:57:12.492+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:57:12.493+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:57:12.493+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:57:12.512+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:57:12.511+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:57:12.512+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:57:12.512+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:57:12.512+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:57:12.557+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2025-02-26T13:58:39.132+0530] {processor.py:157} INFO - Started process (PID=11390) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:58:39.132+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T13:58:39.133+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:58:39.133+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:58:39.152+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:58:39.150+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T13:58:39.152+0530] {logging_mixin.py:154} INFO - [2025-02-26T13:58:39.152+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T13:58:39.152+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T13:58:39.198+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2025-02-26T14:00:16.142+0530] {processor.py:157} INFO - Started process (PID=11514) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:00:16.142+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:00:16.143+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:00:16.143+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:00:16.163+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:00:16.161+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:00:16.163+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:00:16.163+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:00:16.163+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:00:16.210+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T14:01:42.410+0530] {processor.py:157} INFO - Started process (PID=11671) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:01:42.412+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:01:42.412+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:01:42.412+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:01:42.432+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:01:42.431+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:01:42.432+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:01:42.432+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:01:42.432+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:01:42.478+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T14:03:17.533+0530] {processor.py:157} INFO - Started process (PID=11799) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:03:17.534+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:03:17.534+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:03:17.534+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:03:17.555+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:03:17.553+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:03:17.555+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:03:17.555+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:03:17.555+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:03:17.602+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T14:04:54.646+0530] {processor.py:157} INFO - Started process (PID=11995) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:04:54.647+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:04:54.648+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:04:54.648+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:04:54.670+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:04:54.668+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:04:54.670+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:04:54.670+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:04:54.670+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:04:54.718+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-26T14:06:26.026+0530] {processor.py:157} INFO - Started process (PID=12125) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:06:26.027+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:06:26.027+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:06:26.027+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:06:26.048+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:06:26.047+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:06:26.048+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:06:26.048+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:06:26.048+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:06:26.095+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:08:02.229+0530] {processor.py:157} INFO - Started process (PID=12254) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:08:02.230+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:08:02.231+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:08:02.231+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:08:02.252+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:08:02.250+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:08:02.252+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:08:02.252+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:08:02.252+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:08:02.299+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:09:41.349+0530] {processor.py:157} INFO - Started process (PID=12399) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:09:41.350+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:09:41.351+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:09:41.351+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:09:41.374+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:09:41.372+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:09:41.374+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:09:41.374+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:09:41.374+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:09:41.422+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-26T14:11:12.524+0530] {processor.py:157} INFO - Started process (PID=12515) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:11:12.525+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:11:12.525+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:11:12.525+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:11:12.547+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:11:12.546+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:11:12.548+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:11:12.548+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:11:12.548+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:11:12.598+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-26T14:12:50.255+0530] {processor.py:157} INFO - Started process (PID=12641) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:12:50.256+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:12:50.256+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:12:50.256+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:12:50.277+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:12:50.276+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:12:50.277+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:12:50.277+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:12:50.278+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:12:50.324+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:14:19.285+0530] {processor.py:157} INFO - Started process (PID=12755) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:14:19.285+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:14:19.285+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:14:19.285+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:14:19.305+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:14:19.304+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:14:19.305+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:14:19.305+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:14:19.305+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:14:19.352+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T14:16:05.550+0530] {processor.py:157} INFO - Started process (PID=12915) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:16:05.551+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:16:05.551+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:16:05.551+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:16:05.573+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:16:05.571+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:16:05.573+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:16:05.573+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:16:05.573+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:16:05.620+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:17:43.411+0530] {processor.py:157} INFO - Started process (PID=13051) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:17:43.412+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:17:43.413+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:17:43.413+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:17:43.435+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:17:43.433+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:17:43.435+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:17:43.435+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:17:43.435+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:17:43.482+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-26T14:19:22.180+0530] {processor.py:157} INFO - Started process (PID=13177) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:19:22.181+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:19:22.182+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:19:22.182+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:19:22.203+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:19:22.201+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:19:22.203+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:19:22.203+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:19:22.203+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:19:22.250+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-26T14:21:01.661+0530] {processor.py:157} INFO - Started process (PID=13305) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:21:01.663+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:21:01.663+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:21:01.663+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:21:01.684+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:21:01.682+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:21:01.684+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:21:01.684+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:21:01.684+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:21:01.731+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:22:41.215+0530] {processor.py:157} INFO - Started process (PID=13429) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:22:41.216+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:22:41.217+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:22:41.217+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:22:41.239+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:22:41.237+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:22:41.239+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:22:41.239+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:22:41.239+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:22:41.290+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2025-02-26T14:24:22.374+0530] {processor.py:157} INFO - Started process (PID=13574) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:24:22.375+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:24:22.375+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:24:22.375+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:24:22.396+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:24:22.395+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:24:22.396+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:24:22.396+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:24:22.396+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:24:22.443+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:26:17.390+0530] {processor.py:157} INFO - Started process (PID=13747) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:26:17.391+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:26:17.391+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:26:17.391+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:26:17.413+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:26:17.411+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:26:17.413+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:26:17.413+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:26:17.413+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:26:17.463+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-26T14:28:34.667+0530] {processor.py:157} INFO - Started process (PID=13959) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:28:34.668+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:28:34.668+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:28:34.668+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:28:34.692+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:28:34.690+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:28:34.692+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:28:34.692+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:28:34.692+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:28:34.739+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-26T14:30:05.005+0530] {processor.py:157} INFO - Started process (PID=14081) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:30:05.006+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:30:05.006+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:30:05.006+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:30:05.029+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:30:05.027+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:30:05.029+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:30:05.029+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:30:05.029+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:30:05.077+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-26T14:31:38.345+0530] {processor.py:157} INFO - Started process (PID=14199) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:31:38.346+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:31:38.346+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:31:38.346+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:31:38.367+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:31:38.365+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:31:38.367+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:31:38.367+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:31:38.367+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:31:38.413+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T14:33:20.981+0530] {processor.py:157} INFO - Started process (PID=14335) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:33:20.982+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:33:20.983+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:33:20.983+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:33:21.004+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:33:21.002+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:33:21.004+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:33:21.004+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:33:21.004+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:33:21.050+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T14:34:52.016+0530] {processor.py:157} INFO - Started process (PID=14456) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:34:52.017+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:34:52.017+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:34:52.017+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:34:52.037+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:34:52.035+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:34:52.037+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:34:52.037+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:34:52.037+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:34:52.083+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T14:36:21.952+0530] {processor.py:157} INFO - Started process (PID=14582) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:36:21.952+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:36:21.952+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:36:21.952+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:36:21.972+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:36:21.970+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:36:21.972+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:36:21.972+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:36:21.972+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:36:22.018+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-26T14:37:57.915+0530] {processor.py:157} INFO - Started process (PID=14713) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:37:57.916+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:37:57.916+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:37:57.916+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:37:57.937+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:37:57.936+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:37:57.938+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:37:57.938+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:37:57.938+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:37:57.984+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T14:39:37.462+0530] {processor.py:157} INFO - Started process (PID=14852) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:39:37.463+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:39:37.463+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:39:37.463+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:39:37.484+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:39:37.482+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:39:37.484+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:39:37.484+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:39:37.484+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:39:37.531+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:41:17.139+0530] {processor.py:157} INFO - Started process (PID=14983) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:41:17.140+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:41:17.140+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:41:17.140+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:41:17.160+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:41:17.158+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:41:17.160+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:41:17.160+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:41:17.160+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:41:17.206+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T14:42:45.694+0530] {processor.py:157} INFO - Started process (PID=15110) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:42:45.695+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:42:45.695+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:42:45.695+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:42:45.717+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:42:45.715+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:42:45.717+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:42:45.717+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:42:45.717+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:42:45.765+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-26T14:44:17.194+0530] {processor.py:157} INFO - Started process (PID=15236) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:44:17.195+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:44:17.196+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:44:17.196+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:44:17.217+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:44:17.215+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:44:17.217+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:44:17.217+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:44:17.217+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:44:17.263+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:45:52.516+0530] {processor.py:157} INFO - Started process (PID=15366) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:45:52.517+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:45:52.517+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:45:52.517+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:45:52.540+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:45:52.538+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:45:52.540+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:45:52.540+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:45:52.540+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:45:52.587+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-26T14:47:31.482+0530] {processor.py:157} INFO - Started process (PID=15510) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:47:31.483+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:47:31.484+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:47:31.484+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:47:31.505+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:47:31.503+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:47:31.505+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:47:31.505+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:47:31.505+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:47:31.551+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T14:48:58.810+0530] {processor.py:157} INFO - Started process (PID=15647) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:48:58.811+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:48:58.811+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:48:58.811+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:48:58.831+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:48:58.829+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:48:58.831+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:48:58.831+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:48:58.831+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:48:58.878+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T14:50:29.914+0530] {processor.py:157} INFO - Started process (PID=15774) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:50:29.915+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:50:29.915+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:50:29.915+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:50:29.936+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:50:29.934+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:50:29.936+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:50:29.936+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:50:29.936+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:50:29.983+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T14:52:03.883+0530] {processor.py:157} INFO - Started process (PID=15901) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:52:03.883+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:52:03.884+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:52:03.884+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:52:03.904+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:52:03.902+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:52:03.904+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:52:03.904+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:52:03.904+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:52:03.951+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T14:54:18.234+0530] {processor.py:157} INFO - Started process (PID=16051) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:54:18.235+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:54:18.236+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:54:18.236+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:54:18.258+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:54:18.256+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:54:18.258+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:54:18.258+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:54:18.258+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:54:18.305+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-26T14:55:51.118+0530] {processor.py:157} INFO - Started process (PID=16168) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:55:51.119+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:55:51.119+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:55:51.119+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:55:51.139+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:55:51.137+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:55:51.139+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:55:51.139+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:55:51.139+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:55:51.186+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T14:59:59.248+0530] {processor.py:157} INFO - Started process (PID=16294) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:59:59.249+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T14:59:59.249+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:59:59.249+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:59:59.270+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:59:59.268+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T14:59:59.270+0530] {logging_mixin.py:154} INFO - [2025-02-26T14:59:59.270+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T14:59:59.270+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T14:59:59.316+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T15:16:45.754+0530] {processor.py:157} INFO - Started process (PID=16474) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:16:45.755+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:16:45.756+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:16:45.756+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:16:45.777+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:16:45.775+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:16:45.777+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:16:45.777+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:16:45.777+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:16:45.823+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T15:18:15.443+0530] {processor.py:157} INFO - Started process (PID=16614) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:18:15.444+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:18:15.444+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:18:15.444+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:18:15.465+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:18:15.463+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:18:15.465+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:18:15.465+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:18:15.465+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:18:15.510+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T15:19:49.125+0530] {processor.py:157} INFO - Started process (PID=16767) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:19:49.126+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:19:49.127+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:19:49.127+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:19:49.147+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:19:49.145+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:19:49.147+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:19:49.147+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:19:49.147+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:19:49.194+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T15:21:18.557+0530] {processor.py:157} INFO - Started process (PID=16899) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:21:18.558+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:21:18.558+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:21:18.558+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:21:18.579+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:21:18.578+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:21:18.579+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:21:18.579+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:21:18.580+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:21:18.626+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T15:22:49.844+0530] {processor.py:157} INFO - Started process (PID=17029) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:22:49.844+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:22:49.844+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:22:49.844+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:22:49.864+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:22:49.863+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:22:49.864+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:22:49.864+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:22:49.864+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:22:49.911+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T15:24:28.140+0530] {processor.py:157} INFO - Started process (PID=17158) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:24:28.141+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:24:28.141+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:24:28.141+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:24:28.164+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:24:28.162+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:24:28.164+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:24:28.164+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:24:28.164+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:24:28.213+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-26T15:26:07.846+0530] {processor.py:157} INFO - Started process (PID=17292) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:26:07.847+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:26:07.848+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:26:07.848+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:26:07.869+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:26:07.867+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:26:07.869+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:26:07.869+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:26:07.869+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:26:07.915+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T15:27:42.589+0530] {processor.py:157} INFO - Started process (PID=17435) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:27:42.589+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:27:42.590+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:27:42.589+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:27:42.611+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:27:42.609+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:27:42.611+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:27:42.611+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:27:42.611+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:27:42.657+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T15:29:18.202+0530] {processor.py:157} INFO - Started process (PID=17575) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:29:18.203+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:29:18.203+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:29:18.203+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:29:18.225+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:29:18.223+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:29:18.226+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:29:18.226+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:29:18.226+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:29:18.274+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-26T15:30:54.165+0530] {processor.py:157} INFO - Started process (PID=17702) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:30:54.166+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:30:54.167+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:30:54.167+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:30:54.188+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:30:54.186+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:30:54.188+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:30:54.188+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:30:54.188+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:30:54.234+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T15:32:24.417+0530] {processor.py:157} INFO - Started process (PID=17828) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:32:24.417+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:32:24.417+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:32:24.417+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:32:24.437+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:32:24.435+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:32:24.437+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:32:24.437+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:32:24.437+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:32:24.484+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T15:34:09.093+0530] {processor.py:157} INFO - Started process (PID=17956) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:34:09.093+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:34:09.093+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:34:09.093+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:34:09.113+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:34:09.111+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:34:09.113+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:34:09.113+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:34:09.113+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:34:09.159+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-02-26T15:35:50.629+0530] {processor.py:157} INFO - Started process (PID=18090) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:35:50.629+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:35:50.629+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:35:50.629+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:35:50.649+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:35:50.647+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:35:50.649+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:35:50.649+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:35:50.649+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:35:50.696+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T15:37:19.455+0530] {processor.py:157} INFO - Started process (PID=18218) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:37:19.456+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:37:19.457+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:37:19.457+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:37:19.481+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:37:19.478+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:37:19.481+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:37:19.481+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:37:19.481+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:37:19.536+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-02-26T15:38:50.253+0530] {processor.py:157} INFO - Started process (PID=18338) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:38:50.254+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:38:50.254+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:38:50.254+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:38:50.276+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:38:50.274+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:38:50.276+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:38:50.276+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:38:50.276+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:38:50.326+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-26T15:40:31.241+0530] {processor.py:157} INFO - Started process (PID=18466) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:40:31.242+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:40:31.242+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:40:31.242+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:40:31.263+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:40:31.261+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:40:31.263+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:40:31.263+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:40:31.263+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:40:31.310+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T15:42:03.378+0530] {processor.py:157} INFO - Started process (PID=18601) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:42:03.378+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:42:03.379+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:42:03.379+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:42:03.399+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:42:03.397+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:42:03.399+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:42:03.399+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:42:03.399+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:42:03.446+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T15:43:47.476+0530] {processor.py:157} INFO - Started process (PID=18730) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:43:47.477+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:43:47.478+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:43:47.478+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:43:47.501+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:43:47.499+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:43:47.501+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:43:47.501+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:43:47.501+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:43:47.553+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.077 seconds
[2025-02-26T15:45:25.841+0530] {processor.py:157} INFO - Started process (PID=18863) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:45:25.842+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:45:25.842+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:45:25.842+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:45:25.863+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:45:25.861+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:45:25.863+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:45:25.863+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:45:25.863+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:45:25.910+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T15:46:55.970+0530] {processor.py:157} INFO - Started process (PID=18993) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:46:55.971+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:46:55.971+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:46:55.971+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:46:55.992+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:46:55.991+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:46:55.993+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:46:55.993+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:46:55.993+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:46:56.039+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T15:48:32.376+0530] {processor.py:157} INFO - Started process (PID=19114) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:48:32.377+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:48:32.377+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:48:32.377+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:48:32.398+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:48:32.396+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:48:32.398+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:48:32.398+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:48:32.398+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:48:32.445+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T15:50:07.840+0530] {processor.py:157} INFO - Started process (PID=19236) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:50:07.841+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:50:07.841+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:50:07.841+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:50:07.863+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:50:07.861+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:50:07.863+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:50:07.863+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:50:07.863+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:50:07.913+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-26T15:51:39.844+0530] {processor.py:157} INFO - Started process (PID=19359) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:51:39.845+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:51:39.845+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:51:39.845+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:51:39.866+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:51:39.864+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:51:39.866+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:51:39.866+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:51:39.866+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:51:39.913+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T15:53:16.900+0530] {processor.py:157} INFO - Started process (PID=19502) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:53:16.901+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:53:16.902+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:53:16.902+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:53:16.923+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:53:16.921+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:53:16.923+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:53:16.923+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:53:16.923+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:53:16.971+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-26T15:54:50.823+0530] {processor.py:157} INFO - Started process (PID=19626) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:54:50.824+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:54:50.824+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:54:50.824+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:54:50.845+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:54:50.844+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:54:50.845+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:54:50.845+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:54:50.845+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:54:50.892+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T15:56:22.562+0530] {processor.py:157} INFO - Started process (PID=19807) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:56:22.563+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:56:22.563+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:56:22.563+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:56:22.584+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:56:22.583+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:56:22.584+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:56:22.584+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:56:22.585+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:56:22.631+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T15:57:58.572+0530] {processor.py:157} INFO - Started process (PID=19929) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:57:58.572+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:57:58.573+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:57:58.573+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:57:58.594+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:57:58.592+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:57:58.594+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:57:58.594+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:57:58.594+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:57:58.641+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T15:59:28.863+0530] {processor.py:157} INFO - Started process (PID=20060) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:59:28.864+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T15:59:28.864+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:59:28.864+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:59:28.885+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:59:28.884+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T15:59:28.886+0530] {logging_mixin.py:154} INFO - [2025-02-26T15:59:28.886+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T15:59:28.886+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T15:59:28.933+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:00:58.813+0530] {processor.py:157} INFO - Started process (PID=20179) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:00:58.815+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:00:58.815+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:00:58.815+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:00:58.836+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:00:58.834+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:00:58.836+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:00:58.836+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:00:58.836+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:00:58.883+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:02:27.581+0530] {processor.py:157} INFO - Started process (PID=20294) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:02:27.581+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:02:27.582+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:02:27.582+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:02:27.602+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:02:27.600+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:02:27.602+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:02:27.602+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:02:27.602+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:02:27.649+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T16:04:03.475+0530] {processor.py:157} INFO - Started process (PID=20426) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:04:03.476+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:04:03.476+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:04:03.476+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:04:03.497+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:04:03.495+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:04:03.497+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:04:03.497+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:04:03.497+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:04:03.544+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:05:38.569+0530] {processor.py:157} INFO - Started process (PID=20565) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:05:38.570+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:05:38.570+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:05:38.570+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:05:38.592+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:05:38.590+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:05:38.593+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:05:38.592+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:05:38.593+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:05:38.642+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-26T16:07:14.950+0530] {processor.py:157} INFO - Started process (PID=20698) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:07:14.951+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:07:14.951+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:07:14.951+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:07:14.973+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:07:14.971+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:07:14.973+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:07:14.973+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:07:14.973+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:07:15.021+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-26T16:08:57.500+0530] {processor.py:157} INFO - Started process (PID=20827) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:08:57.501+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:08:57.501+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:08:57.501+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:08:57.523+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:08:57.521+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:08:57.523+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:08:57.523+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:08:57.523+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:08:57.572+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-26T16:10:37.630+0530] {processor.py:157} INFO - Started process (PID=20962) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:10:37.631+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:10:37.631+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:10:37.631+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:10:37.652+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:10:37.651+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:10:37.653+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:10:37.652+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:10:37.653+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:10:37.702+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-26T16:12:16.875+0530] {processor.py:157} INFO - Started process (PID=21101) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:12:16.876+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:12:16.876+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:12:16.876+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:12:16.897+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:12:16.896+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:12:16.898+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:12:16.897+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:12:16.898+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:12:16.944+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:13:49.386+0530] {processor.py:157} INFO - Started process (PID=21236) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:13:49.387+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:13:49.387+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:13:49.387+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:13:49.409+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:13:49.407+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:13:49.409+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:13:49.409+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:13:49.409+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:13:49.456+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:15:23.965+0530] {processor.py:157} INFO - Started process (PID=21360) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:15:23.965+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:15:23.965+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:15:23.965+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:15:23.985+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:15:23.984+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:15:23.986+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:15:23.985+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:15:23.986+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:15:24.032+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T16:16:52.345+0530] {processor.py:157} INFO - Started process (PID=21480) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:16:52.346+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:16:52.346+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:16:52.346+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:16:52.366+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:16:52.364+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:16:52.366+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:16:52.366+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:16:52.366+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:16:52.413+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T16:18:22.250+0530] {processor.py:157} INFO - Started process (PID=21602) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:18:22.250+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:18:22.251+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:18:22.251+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:18:22.270+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:18:22.269+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:18:22.271+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:18:22.271+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:18:22.271+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:18:22.317+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T16:19:57.575+0530] {processor.py:157} INFO - Started process (PID=21725) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:19:57.575+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:19:57.575+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:19:57.575+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:19:57.595+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:19:57.593+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:19:57.595+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:19:57.595+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:19:57.595+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:19:57.642+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-26T16:21:26.230+0530] {processor.py:157} INFO - Started process (PID=21855) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:21:26.231+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:21:26.231+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:21:26.231+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:21:26.252+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:21:26.251+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:21:26.253+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:21:26.252+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:21:26.253+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:21:26.299+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T16:23:00.602+0530] {processor.py:157} INFO - Started process (PID=21985) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:23:00.603+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:23:00.604+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:23:00.604+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:23:00.626+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:23:00.624+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:23:00.626+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:23:00.626+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:23:00.626+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:23:00.674+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-26T16:24:35.390+0530] {processor.py:157} INFO - Started process (PID=22104) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:24:35.391+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:24:35.392+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:24:35.392+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:24:35.416+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:24:35.414+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:24:35.416+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:24:35.416+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:24:35.416+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:24:35.467+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.077 seconds
[2025-02-26T16:26:10.528+0530] {processor.py:157} INFO - Started process (PID=22230) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:26:10.529+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:26:10.530+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:26:10.530+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:26:10.551+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:26:10.549+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:26:10.551+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:26:10.551+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:26:10.551+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:26:10.598+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:27:44.533+0530] {processor.py:157} INFO - Started process (PID=22391) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:27:44.534+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:27:44.535+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:27:44.534+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:27:44.556+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:27:44.554+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:27:44.556+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:27:44.556+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:27:44.556+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:27:44.602+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:29:23.374+0530] {processor.py:157} INFO - Started process (PID=22516) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:29:23.375+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:29:23.375+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:29:23.375+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:29:23.396+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:29:23.394+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:29:23.396+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:29:23.396+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:29:23.396+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:29:23.443+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:30:53.339+0530] {processor.py:157} INFO - Started process (PID=22635) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:30:53.339+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:30:53.339+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:30:53.339+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:30:53.360+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:30:53.359+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:30:53.361+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:30:53.361+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:30:53.361+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:30:53.407+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-26T16:32:29.656+0530] {processor.py:157} INFO - Started process (PID=22764) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:32:29.657+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:32:29.658+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:32:29.658+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:32:29.679+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:32:29.678+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:32:29.679+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:32:29.679+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:32:29.679+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:32:29.727+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-26T16:34:04.912+0530] {processor.py:157} INFO - Started process (PID=22892) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:34:04.913+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:34:04.913+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:34:04.913+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:34:04.935+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:34:04.933+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:34:04.935+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:34:04.935+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:34:04.935+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:34:04.982+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-26T16:35:49.224+0530] {processor.py:157} INFO - Started process (PID=23037) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:35:49.225+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:35:49.225+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:35:49.225+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:35:49.248+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:35:49.246+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:35:49.248+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:35:49.248+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:35:49.248+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:35:49.297+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-26T16:37:29.861+0530] {processor.py:157} INFO - Started process (PID=23168) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:37:29.862+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:37:29.863+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:37:29.863+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:37:29.884+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:37:29.883+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:37:29.885+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:37:29.884+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:37:29.885+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:37:29.935+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-26T16:39:08.765+0530] {processor.py:157} INFO - Started process (PID=23688) to work on /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:39:08.767+0530] {processor.py:829} INFO - Processing file /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T16:39:08.767+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:39:08.767+0530] {dagbag.py:536} INFO - Filling up the DagBag from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:39:08.788+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:39:08.786+0530] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T16:39:08.788+0530] {logging_mixin.py:154} INFO - [2025-02-26T16:39:08.788+0530] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T16:39:08.788+0530] {processor.py:841} WARNING - No viable dags retrieved from /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T16:39:08.835+0530] {processor.py:179} INFO - Processing /Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
